### PR TITLE
Fix #59 "Bad data passed in;" When trying to forward reply to emails

### LINKED ISSUE #59: "Bad data passed in;" When trying to forward or reply to emails
#### Issue
Fresh installation of SuiteCRM 8.0.1 and everything else seems to be working correctly. However after I have imported an Email, whenever I open up the actual Email record and hit Reply, Reply to All or Forward, I get the “Bad data passed in; Return to Home” error.
When I go composing a new email or when I hit Reply from the Email Dashlet without actually opening up the Email record, it works without issues.

#### Expected Behavior
The modal window with e-mail composition should open when I try to reply or forward an imported e-mail.

#### Actual Behavior
A "Bad data passed in;" error is displayed.

#### Steps to Reproduce

1. Import an e-mail
2. Open the e-mail
3. Select Actions->Reply
4. Note the error being displayed instead of modal window

#### Context
I am currently unable to effectively work with e-mails inside SuiteCRM. 

#### Your Environment

* SuiteCRM Version used: 8.0.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 96.0.4664.110 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4
* Operating System and version (e.g Ubuntu 16.04):Debian 11

### PR DESCRIPTION
**Pull request by abuzarfaris**
- return_action and module parameters were being passed twice changed it to passed once

## Description
fixed the detailviewdefs of Emails module to pass return_action and module parameters in url once

## Motivation and Context
Trying to reply to imported emails results in Bad data passed error

## How To Test This
1. Import an e-mail
2. Open the e-mail
3. Select Actions->Reply
4. The reply window opens properly

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by clemente-raposo** [comment]
Hi @abuzarfaris, @jack7anderson7 

This PR also applied in SuiteCRM 7.x. So I think we should move it to the 7.x repo: https://github.com/salesagility/SuiteCRM
And it will be pulled into Suite 8 afterwards, using the git subtree.

**Comment by abuzarfaris** [comment]
> Hi @abuzarfaris, @jack7anderson7
> 
> @abuzarfaris thank you for your PR
> 
> This PR also applied in SuiteCRM 7.x. So I think we should move it to the 7.x repo: https://github.com/salesagility/SuiteCRM And it will be pulled into Suite 8 afterwards, using the git subtree.

In SuiteCRM 8 this breaks the functionality while in SuiteCRM 7.x it just looks untidy

**Comment by clemente-raposo** [comment]
> > Hi @abuzarfaris, @jack7anderson7
> > @abuzarfaris thank you for your PR
> > This PR also applied in SuiteCRM 7.x. So I think we should move it to the 7.x repo: https://github.com/salesagility/SuiteCRM And it will be pulled into Suite 8 afterwards, using the git subtree.
> 
> In SuiteCRM 8 this breaks the functionality while in SuiteCRM 7.x it just looks untidy

Hi @abuzarfaris, I get what you mean now.

File: public/legacy/modules/Emails/metadata/detailviewdefs.php [hunk 1]
```diff
@@ -50,14 +50,15 @@
                     'customCode' => '<input type=button onclick="window.location.href=\'index.php?module=Emails&action=DeleteFromImap&folder=INBOX.TestInbox&folder=inbound&inbound_email_record={$bean->inbound_email_record}&uid={$bean->uid}&msgno={$bean->msgNo}&record={$bean->id}&return_module=Emails&return_action=index\';" value="{$MOD.LBL_BUTTON_DELETE_IMAP}">'
                 ],
                 'FIND_DUPLICATES',
+                //Fix #59 - "Bad data passed in;" When trying to forward or reply to emails
```
Comment (clemente-raposo) [inline public/legacy/modules/Emails/metadata/detailviewdefs.php:53]: Hi @abuzarfaris,

Could we remove the comment like we did on the other ones please?

Comment (abuzarfaris) [reply public/legacy/modules/Emails/metadata/detailviewdefs.php]: @clemente-raposo Updated removed comment

**Review by jack7anderson7 — APPROVED** [review]
